// src/samples/angular/movies-zh.js
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-movies',
  template: `
    <div class="divide-y divide-gray-100">
      <app-nav>
        <app-nav-item routerLink="/new" [isActive]="true">新片上映</app-nav-item>
        <app-nav-item routerLink="/top">熱門電影</app-nav-item>
        <app-nav-item routerLink="/picks">文森精選</app-nav-item>
      </app-nav>
      <app-list>
        <app-list-item *ngFor="let movie of movies" [movie]="movie"></app-list-item>
      </app-list>
    </div>
  `,
})

export class MoviesComponent {
  @Input() movies!: {
    image: string
    title: string
    starRating: string
    rating: string
    year: string
    genre: string
    runtime: string
    cast: string
  }[]
}

// src/samples/react/movies-zh.jsx
import Nav from './Nav.js'
import NavItem from './NavItem.js'
import List from './List.js'
import ListItem from './ListItem.js'

export default function Movies({ movies }) {
  return (
    <div className="divide-y divide-gray-100">
      <Nav>
        <NavItem href="/new" isActive>新片上映</NavItem>
        <NavItem href="/top">熱門電影</NavItem>
        <NavItem href="/picks">文森精選</NavItem>
      </Nav>
      <List>
        {movies.map((movie) => (
          <ListItem key={movie.id} movie={movie} />
        ))}
      </List>
    </div>
  )
}
